# Generated by Django 3.2.20 on 2023-07-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20230717_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='new', max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(default='Task', max_length=200, verbose_name='Type'),
        ),
    ]
