# Generated by Django 3.2.20 on 2023-07-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='to_do_list.project', verbose_name='project'),
        ),
    ]
