# Generated by Django 3.2.20 on 2023-09-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='to_do_list.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='to_do_list.type', verbose_name='type'),
        ),
    ]
